server:
  port: 9999
  
spring:
  datasource:
    url: jdbc:mysql://172.16.0.99:13306/lbz?characterEncoding=UTF-8
    username: lbz
    password: DeMcpFH52yPfCX%Z
    driver-class-name: com.mysql.jdbc.Driver
  activemq:
    broker-url: tcp://ac.mqtt.lubanzhang.net:61616
    user: lbz
    password: lbz@mq@admin@2017
    in-memory: true
    pool:
      enabled: false
  jms:
    pub-sub-domain: true
mybatis:
  type-aliases-package: com.didispace.entity
  mapper-locations: 
  - classpath:mybatis/mapper/*.xml 
  